# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180917_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucherrequest',
            name='rejection_reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
