# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180917_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_voucher_requests', to='app.Account'),
        ),
        migrations.AlterField(
            model_name='voucherrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_requests', to='app.Account'),
        ),
    ]
