# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180917_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='discountvoucher',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucherrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected')], null=True, max_length=20),
        ),
    ]
