# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180917_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
